### ISSUE TITLE
Very fast blinking on iPhone

### ISSUE THREAD

**Issue by Kolombiken** [5t3ph/buttonbuddy#2]
### This is a:

[X] Accessibility/usability bug

When scrolling the site, the clouds blink very fast. At times also part of the buttons blink as well. When you scroll and stop a cloud can continue to blink. This is visible in Safari on an iPhone Xs, iOS 14.2.  

I tried to do a screen recording but as soon as I hit record the blinking stopped. When stopping the recording the blinking starts again. 

I think this would be good to look into since it's a thing that can easily be triggering. For me this kind of blinking immediately triggers a headache. (Which makes it even harder for me to debug 😞 )

**Comment by 5t3ph** [comment]
Oh I finally got it to reproduce. It's like it's trying to redraw the radial-gradient once scrolling stops I think? Hmm I will try an alternate way to do the cloud, maybe an SVG. Thanks, I'll report back after I look at it more this evening!

**Comment by 5t3ph** [comment]
Hi @Kolombiken - I just pushed an update, I _think_ it was a CSS stacking issue causing repaint problems. Please let me know if it's still present for you! I tried to reproduce after this fix and could not, and I happen to have the same model and version as you for iPhone. I'm not sure if it will need a cache clear first, I just did browser refresh a few times. I really appreciate you taking time to provide details especially since it causes you pain, which I'm very sorry for 😢  Does the "slide in" of the speech bubble bother you as well? If so, would reduced speed help?

**Comment by Kolombiken** [comment]
Works very well now! No blinking at all. Awesome!
I have reduce motion turned on since it sometimes helps against triggering animations. But I tried with it both on and off to check the difference and to be honest I prefer the animation to the clouds "popping in" without an animation. If it's not too tricky I think the best would be for the clouds to be there by default for people that have reduce motion turned on. 

Anyway thanks for being open to feedback. I don't think I would have bothered reporting this at all if you wouldn't have asked about issues. 😄

**Comment by 5t3ph** [comment]
@Kolombiken I'm glad to know it is resolved, I appreciate you following up especially given the fact you were taking a chance at another headache!

I previously had a query for `prefers-reduced-motion` that was essentially "fast-forwarding" the animation so I've now completely disallowed it if that setting is active 👍 

Thanks again!!
